
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zan
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Goriva = new javax.swing.ButtonGroup();
        OsnovnoZavarovanje = new javax.swing.ButtonGroup();
        KaskoZavarovanje = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jOptionPane1 = new javax.swing.JOptionPane();
        jfc = new javax.swing.JFileChooser();
        CelotaSave = new javax.swing.JTextField();
        Panela_Zavarovanec = new javax.swing.JPanel();
        Prosta = new javax.swing.JPanel();
        PodatkiOZavarovancu = new javax.swing.JPanel();
        ImeLabel = new javax.swing.JLabel();
        ImeField = new javax.swing.JTextField();
        PriimekLabel = new javax.swing.JLabel();
        PriimekField = new javax.swing.JTextField();
        DatumRojLabel = new javax.swing.JLabel();
        UlicaLabel = new javax.swing.JLabel();
        UlicaField = new javax.swing.JTextField();
        HisnaLabel = new javax.swing.JLabel();
        HisnaField = new javax.swing.JTextField();
        KrajLabel = new javax.swing.JLabel();
        KrajField = new javax.swing.JTextField();
        PostaLabel = new javax.swing.JLabel();
        IzkusnjeLabel = new javax.swing.JLabel();
        IzkusnjeCombo = new javax.swing.JComboBox<>();
        DRdan = new javax.swing.JComboBox<>();
        DRmesec = new javax.swing.JComboBox<>();
        DRleto = new javax.swing.JComboBox<>();
        PostaSpinner = new javax.swing.JSpinner();
        Panela_Vozilo = new javax.swing.JPanel();
        Prosta1 = new javax.swing.JPanel();
        PodatkiOZavarovancu1 = new javax.swing.JPanel();
        ZnamkaLabel = new javax.swing.JLabel();
        ZnamkaField = new javax.swing.JTextField();
        OznakaLabel = new javax.swing.JLabel();
        OznakaField = new javax.swing.JTextField();
        MocLabel = new javax.swing.JLabel();
        MocSpinner = new javax.swing.JSpinner();
        VrstaVozilaLabel = new javax.swing.JLabel();
        VrstaVozilaCombo = new javax.swing.JComboBox<>();
        GorivoLabel = new javax.swing.JLabel();
        BencinRadio = new javax.swing.JRadioButton();
        NaftaRadio = new javax.swing.JRadioButton();
        ElektrikaRadio = new javax.swing.JRadioButton();
        PlinRadio = new javax.swing.JRadioButton();
        KubLabel = new javax.swing.JLabel();
        KubSpinner = new javax.swing.JSpinner();
        BarvaLabel = new javax.swing.JLabel();
        SedeziLabel = new javax.swing.JLabel();
        SedeziSpinner = new javax.swing.JSpinner();
        BarvaComboBox = new javax.swing.JComboBox<>();
        PodatkiORegistraciji = new javax.swing.JPanel();
        DatumRegistracijeLabel = new javax.swing.JLabel();
        KrajRegistracijeLabel = new javax.swing.JLabel();
        KrajRegistracijeField = new javax.swing.JTextField();
        RegOznacbaLabel = new javax.swing.JLabel();
        RegOznacbaField = new javax.swing.JTextField();
        DPdan = new javax.swing.JComboBox<>();
        DPmesec = new javax.swing.JComboBox<>();
        DPleto = new javax.swing.JComboBox<>();
        KrajRegistracijeNapaka = new javax.swing.JLabel();
        Panela_Zavarovanje = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        Prosta2 = new javax.swing.JPanel();
        PodatkiOZavarovanju = new javax.swing.JPanel();
        ZnamkaLabel2 = new javax.swing.JLabel();
        MocLabel2 = new javax.swing.JLabel();
        AO = new javax.swing.JRadioButton();
        AOplus = new javax.swing.JRadioButton();
        Polnozav = new javax.swing.JRadioButton();
        Franzav = new javax.swing.JRadioButton();
        Brezzav = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        ZStekel = new javax.swing.JCheckBox();
        ZPark = new javax.swing.JCheckBox();
        ZTretja = new javax.swing.JCheckBox();
        ZPotn = new javax.swing.JCheckBox();
        ZGum = new javax.swing.JCheckBox();
        ZKraji = new javax.swing.JCheckBox();
        ZToci = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PonastaviVnose = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        CelotaSave.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panela_Zavarovanec.setFont(Panela_Zavarovanec.getFont());
        Panela_Zavarovanec.setLayout(new javax.swing.BoxLayout(Panela_Zavarovanec, javax.swing.BoxLayout.LINE_AXIS));

        Prosta.setFont(Prosta.getFont());

        PodatkiOZavarovancu.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki O Zavarovancu"));

        ImeLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ImeLabel.setText("Ime:");

        ImeField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ImeField.setText("Vpišite Ime");
        ImeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fgime(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ImeFieldFocusLost(evt);
            }
        });

        PriimekLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        PriimekLabel.setText("Priimek:");

        PriimekField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        PriimekField.setText("Vpišite Priimek");
        PriimekField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fgpriimek(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PriimekFieldFocusLost(evt);
            }
        });

        DatumRojLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DatumRojLabel.setText("Datum Rojstva:");

        UlicaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        UlicaLabel.setText("Ulica:");

        UlicaField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        UlicaField.setText("Vpišite Ulico");
        UlicaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fgulica(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UlicaFieldFocusLost(evt);
            }
        });
        UlicaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APulica(evt);
            }
        });

        HisnaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        HisnaLabel.setText("Hišna Št:");

        HisnaField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        HisnaField.setText("Vpišite Hišno Številko");
        HisnaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fghisna(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HisnaFieldFocusLost(evt);
            }
        });

        KrajLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        KrajLabel.setText("Kraj:");

        KrajField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        KrajField.setText("Vpišite Kraj");
        KrajField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fgkraj(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KrajFieldFocusLost(evt);
            }
        });
        KrajField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KrajFieldActionPerformed(evt);
            }
        });

        PostaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        PostaLabel.setText("Pošta:");

        IzkusnjeLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        IzkusnjeLabel.setText("Izkušnje:");

        IzkusnjeCombo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        IzkusnjeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Izkušen voznik", "Mladi voznik" }));

        DRdan.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DRdan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        DRmesec.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DRmesec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "Marec ", "April", "Maj", "Junij", "Julij", "Avgust", "September", "Oktober", "November", "December" }));
        DRmesec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRmesecActionPerformed(evt);
            }
        });

        DRleto.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DRleto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));

        PostaSpinner.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        PostaSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)1000), Short.valueOf((short)1000), Short.valueOf((short)9999), Short.valueOf((short)1)));
        PostaSpinner.setToolTipText("");
        PostaSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(PostaSpinner, "0000"));

        javax.swing.GroupLayout PodatkiOZavarovancuLayout = new javax.swing.GroupLayout(PodatkiOZavarovancu);
        PodatkiOZavarovancu.setLayout(PodatkiOZavarovancuLayout);
        PodatkiOZavarovancuLayout.setHorizontalGroup(
            PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                        .addComponent(ImeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                        .addComponent(PriimekLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImeField)
                            .addComponent(PriimekField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                        .addComponent(DatumRojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DRdan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(DRmesec, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DRleto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                        .addComponent(IzkusnjeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IzkusnjeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UlicaLabel)
                    .addComponent(HisnaLabel)
                    .addComponent(KrajLabel)
                    .addComponent(PostaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KrajField)
                    .addComponent(HisnaField, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(UlicaField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PodatkiOZavarovancuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PostaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        PodatkiOZavarovancuLayout.setVerticalGroup(
            PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UlicaLabel)
                            .addComponent(UlicaField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HisnaLabel)
                            .addComponent(HisnaField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KrajLabel)
                            .addComponent(KrajField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PostaLabel)
                            .addComponent(PostaSpinner)))
                    .addGroup(PodatkiOZavarovancuLayout.createSequentialGroup()
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImeLabel)
                            .addComponent(ImeField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriimekLabel)
                            .addComponent(PriimekField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatumRojLabel)
                            .addComponent(DRdan)
                            .addComponent(DRmesec)
                            .addComponent(DRleto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PodatkiOZavarovancuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IzkusnjeLabel)
                            .addComponent(IzkusnjeCombo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProstaLayout = new javax.swing.GroupLayout(Prosta);
        Prosta.setLayout(ProstaLayout);
        ProstaLayout.setHorizontalGroup(
            ProstaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProstaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PodatkiOZavarovancu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProstaLayout.setVerticalGroup(
            ProstaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProstaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PodatkiOZavarovancu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panela_Zavarovanec.add(Prosta);

        getContentPane().add(Panela_Zavarovanec, java.awt.BorderLayout.NORTH);

        Panela_Vozilo.setFont(Panela_Vozilo.getFont());
        Panela_Vozilo.setLayout(new java.awt.BorderLayout());

        Prosta1.setFont(Prosta1.getFont());

        PodatkiOZavarovancu1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki O Vozilu"));
        PodatkiOZavarovancu1.setFont(PodatkiOZavarovancu1.getFont());

        ZnamkaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZnamkaLabel.setText("Znamka:");

        ZnamkaField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZnamkaField.setText("Vpišite Znamko");
        ZnamkaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ZnamkaFieldfgime(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ZnamkaFieldFocusLost(evt);
            }
        });
        ZnamkaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZnamkaFieldActionPerformed(evt);
            }
        });

        OznakaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        OznakaLabel.setText("Oznaka:");

        OznakaField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        OznakaField.setText("Vpišite Oznako");
        OznakaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OznakaFieldfgpriimek(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                OznakaFieldFocusLost(evt);
            }
        });

        MocLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        MocLabel.setText("Moč (kw):");

        MocSpinner.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        MocSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        VrstaVozilaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        VrstaVozilaLabel.setText("Vrsta Vozila:");

        VrstaVozilaCombo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        VrstaVozilaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Osebni Avto", "Motor", "Traktor", "Tovornjak", "Avtobus" }));

        GorivoLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        GorivoLabel.setText("Gorivo:");

        Goriva.add(BencinRadio);
        BencinRadio.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        BencinRadio.setForeground(new java.awt.Color(0, 0, 255));
        BencinRadio.setText("Bencin");

        Goriva.add(NaftaRadio);
        NaftaRadio.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        NaftaRadio.setForeground(new java.awt.Color(0, 0, 255));
        NaftaRadio.setText("Nafta");

        Goriva.add(ElektrikaRadio);
        ElektrikaRadio.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ElektrikaRadio.setForeground(new java.awt.Color(0, 0, 255));
        ElektrikaRadio.setText("Elektrika");

        Goriva.add(PlinRadio);
        PlinRadio.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        PlinRadio.setForeground(new java.awt.Color(0, 0, 255));
        PlinRadio.setText("Plin");
        PlinRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlinRadioActionPerformed(evt);
            }
        });

        KubLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        KubLabel.setText("Prostornina V Kubičnih Metrih:");

        KubSpinner.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        KubSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        BarvaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        BarvaLabel.setText("Barva:");

        SedeziLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        SedeziLabel.setText("Število Sedežev:");

        SedeziSpinner.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        SedeziSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        BarvaComboBox.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        BarvaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bela", "Modra", "Rdeča", "Rumena", "Siva", "Srebrna", "Vijolična", "Zelena", "Črna" }));

        javax.swing.GroupLayout PodatkiOZavarovancu1Layout = new javax.swing.GroupLayout(PodatkiOZavarovancu1);
        PodatkiOZavarovancu1.setLayout(PodatkiOZavarovancu1Layout);
        PodatkiOZavarovancu1Layout.setHorizontalGroup(
            PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodatkiOZavarovancu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodatkiOZavarovancu1Layout.createSequentialGroup()
                        .addComponent(OznakaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZnamkaField, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(OznakaField, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)))
                    .addGroup(PodatkiOZavarovancu1Layout.createSequentialGroup()
                        .addComponent(MocLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MocSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PodatkiOZavarovancu1Layout.createSequentialGroup()
                        .addComponent(ZnamkaLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PodatkiOZavarovancu1Layout.createSequentialGroup()
                        .addComponent(VrstaVozilaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VrstaVozilaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodatkiOZavarovancu1Layout.createSequentialGroup()
                        .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SedeziLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KubLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KubSpinner)
                            .addComponent(SedeziSpinner)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PodatkiOZavarovancu1Layout.createSequentialGroup()
                        .addComponent(BarvaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BarvaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PodatkiOZavarovancu1Layout.createSequentialGroup()
                        .addComponent(GorivoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BencinRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NaftaRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ElektrikaRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PlinRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        PodatkiOZavarovancu1Layout.setVerticalGroup(
            PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PodatkiOZavarovancu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZnamkaLabel)
                    .addComponent(ZnamkaField)
                    .addComponent(GorivoLabel)
                    .addComponent(BencinRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NaftaRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ElektrikaRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlinRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OznakaLabel)
                    .addComponent(OznakaField)
                    .addComponent(KubLabel)
                    .addComponent(KubSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SedeziLabel)
                    .addComponent(SedeziSpinner)
                    .addComponent(MocSpinner)
                    .addComponent(MocLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BarvaLabel)
                        .addComponent(BarvaComboBox))
                    .addGroup(PodatkiOZavarovancu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VrstaVozilaLabel)
                        .addComponent(VrstaVozilaCombo))))
        );

        PodatkiORegistraciji.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki O Registraciji"));
        PodatkiORegistraciji.setFont(PodatkiORegistraciji.getFont());

        DatumRegistracijeLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DatumRegistracijeLabel.setText("Datum Prve Registracije:");

        KrajRegistracijeLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        KrajRegistracijeLabel.setText("Kraj Prve Registracije:");

        KrajRegistracijeField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        KrajRegistracijeField.setText("Vpišite Kraj Prve Registracije");
        KrajRegistracijeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KrajRegistracijeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KrajRegistracijeFieldFocusLost(evt);
            }
        });

        RegOznacbaLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        RegOznacbaLabel.setText("Registracijska označba:");

        RegOznacbaField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        RegOznacbaField.setText("Vpišite Registracijsko Označbo");
        RegOznacbaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RegOznacbaFieldfgime(evt);
            }
        });

        DPdan.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DPdan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        DPmesec.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DPmesec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "Marec ", "April", "Maj", "Junij", "Julij", "Avgust", "September", "Oktober", "November", "December" }));
        DPmesec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPmesecActionPerformed(evt);
            }
        });

        DPleto.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        DPleto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));

        KrajRegistracijeNapaka.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        javax.swing.GroupLayout PodatkiORegistracijiLayout = new javax.swing.GroupLayout(PodatkiORegistraciji);
        PodatkiORegistraciji.setLayout(PodatkiORegistracijiLayout);
        PodatkiORegistracijiLayout.setHorizontalGroup(
            PodatkiORegistracijiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodatkiORegistracijiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PodatkiORegistracijiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KrajRegistracijeLabel)
                    .addComponent(RegOznacbaLabel)
                    .addComponent(DatumRegistracijeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PodatkiORegistracijiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KrajRegistracijeField)
                    .addGroup(PodatkiORegistracijiLayout.createSequentialGroup()
                        .addComponent(DPdan, 0, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DPmesec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DPleto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(RegOznacbaField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KrajRegistracijeNapaka)
                .addGap(360, 360, 360))
        );
        PodatkiORegistracijiLayout.setVerticalGroup(
            PodatkiORegistracijiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodatkiORegistracijiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PodatkiORegistracijiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DPdan)
                    .addComponent(DPmesec)
                    .addComponent(DPleto)
                    .addComponent(DatumRegistracijeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PodatkiORegistracijiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KrajRegistracijeLabel)
                    .addComponent(KrajRegistracijeField)
                    .addComponent(KrajRegistracijeNapaka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PodatkiORegistracijiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegOznacbaLabel)
                    .addComponent(RegOznacbaField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Prosta1Layout = new javax.swing.GroupLayout(Prosta1);
        Prosta1.setLayout(Prosta1Layout);
        Prosta1Layout.setHorizontalGroup(
            Prosta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prosta1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Prosta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PodatkiOZavarovancu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PodatkiORegistraciji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Prosta1Layout.setVerticalGroup(
            Prosta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prosta1Layout.createSequentialGroup()
                .addComponent(PodatkiOZavarovancu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(PodatkiORegistraciji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panela_Vozilo.add(Prosta1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Panela_Vozilo, java.awt.BorderLayout.CENTER);

        Panela_Zavarovanje.setFont(Panela_Zavarovanje.getFont());
        Panela_Zavarovanje.setLayout(new java.awt.BorderLayout());

        status.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        status.setText("Status: Pripravljeno za vnos podatkov");
        Panela_Zavarovanje.add(status, java.awt.BorderLayout.SOUTH);

        Prosta2.setFont(Prosta2.getFont());

        PodatkiOZavarovanju.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki O Zavarovanju"));
        PodatkiOZavarovanju.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        ZnamkaLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZnamkaLabel2.setText("Osnovno Zavarovanje:");

        MocLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        MocLabel2.setText("Kasko zavarovanje:");

        OsnovnoZavarovanje.add(AO);
        AO.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        AO.setForeground(new java.awt.Color(0, 0, 255));
        AO.setText("AO");
        AO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AOActionPerformed(evt);
            }
        });

        OsnovnoZavarovanje.add(AOplus);
        AOplus.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        AOplus.setForeground(new java.awt.Color(0, 0, 255));
        AOplus.setText("AO+");
        AOplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AOplusActionPerformed(evt);
            }
        });

        KaskoZavarovanje.add(Polnozav);
        Polnozav.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        Polnozav.setForeground(new java.awt.Color(0, 0, 255));
        Polnozav.setText("Polno");

        KaskoZavarovanje.add(Franzav);
        Franzav.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        Franzav.setForeground(new java.awt.Color(0, 0, 255));
        Franzav.setText("Odbita Franšiza");
        Franzav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FranzavActionPerformed(evt);
            }
        });

        KaskoZavarovanje.add(Brezzav);
        Brezzav.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        Brezzav.setForeground(new java.awt.Color(0, 0, 255));
        Brezzav.setText("Brez");
        Brezzav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrezzavActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel1.setText("Dodatno Zavarovanje:");

        ZStekel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZStekel.setForeground(new java.awt.Color(0, 0, 255));
        ZStekel.setText("Zavarovanje Stekel");

        ZPark.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZPark.setForeground(new java.awt.Color(0, 0, 255));
        ZPark.setText("Zavarovanje Na Parkirišču");
        ZPark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZParkActionPerformed(evt);
            }
        });

        ZTretja.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZTretja.setForeground(new java.awt.Color(0, 0, 255));
        ZTretja.setText("Zavarovanje Tretje Osebe");
        ZTretja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZTretjaActionPerformed(evt);
            }
        });

        ZPotn.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZPotn.setForeground(new java.awt.Color(0, 0, 255));
        ZPotn.setText("Zavarovanje Potnikov");
        ZPotn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZPotnActionPerformed(evt);
            }
        });

        ZGum.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZGum.setForeground(new java.awt.Color(0, 0, 255));
        ZGum.setText("Zavarovanje Gum");

        ZKraji.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZKraji.setForeground(new java.awt.Color(0, 0, 255));
        ZKraji.setText("Zavarovanje Proti Kraji");

        ZToci.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ZToci.setForeground(new java.awt.Color(0, 0, 255));
        ZToci.setText("Zavarovanje Proti Toči");

        javax.swing.GroupLayout PodatkiOZavarovanjuLayout = new javax.swing.GroupLayout(PodatkiOZavarovanju);
        PodatkiOZavarovanju.setLayout(PodatkiOZavarovanjuLayout);
        PodatkiOZavarovanjuLayout.setHorizontalGroup(
            PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                        .addComponent(ZnamkaLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AOplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142))
                    .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                        .addComponent(MocLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Polnozav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Franzav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Brezzav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel1)
                    .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                        .addComponent(ZToci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(240, 240, 240))
                    .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                        .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                                .addComponent(ZStekel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(47, 47, 47))
                            .addComponent(ZTretja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                                .addComponent(ZGum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)))
                        .addGap(16, 16, 16)
                        .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                                .addComponent(ZKraji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                                .addComponent(ZPotn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(29, 29, 29))
                            .addComponent(ZPark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(421, 421, 421))
        );
        PodatkiOZavarovanjuLayout.setVerticalGroup(
            PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodatkiOZavarovanjuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZnamkaLabel2)
                    .addComponent(AO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AOplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MocLabel2)
                    .addComponent(Polnozav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Franzav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Brezzav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZStekel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ZPark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZTretja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ZPotn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PodatkiOZavarovanjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZGum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ZKraji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ZToci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Prosta2Layout = new javax.swing.GroupLayout(Prosta2);
        Prosta2.setLayout(Prosta2Layout);
        Prosta2Layout.setHorizontalGroup(
            Prosta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prosta2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PodatkiOZavarovanju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Prosta2Layout.setVerticalGroup(
            Prosta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Prosta2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PodatkiOZavarovanju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panela_Zavarovanje.add(Prosta2, java.awt.BorderLayout.CENTER);

        getContentPane().add(Panela_Zavarovanje, java.awt.BorderLayout.PAGE_END);

        jMenu1.setMnemonic('D');
        jMenu1.setText("Datoteka");
        jMenu1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('S');
        jMenuItem1.setText("Shrani");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('P');
        jMenu2.setText("Popravi");
        jMenu2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        PonastaviVnose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PonastaviVnose.setMnemonic('P');
        PonastaviVnose.setText("Ponastavi Vnose");
        PonastaviVnose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PonastaviVnoseActionPerformed(evt);
            }
        });
        jMenu2.add(PonastaviVnose);

        jMenuBar1.add(jMenu2);

        Pomoc.setMnemonic('P');
        Pomoc.setText("Pomoč");
        Pomoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PomocActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('K');
        jMenuItem2.setText("Kontakt");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Pomoc.add(jMenuItem2);

        jMenuBar1.add(Pomoc);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fgime(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fgime
        ImeField.setText("");
        ImeField.setForeground(Color.black);
    }//GEN-LAST:event_fgime

    private void KrajFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KrajFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KrajFieldActionPerformed

    private void fgpriimek(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fgpriimek
        PriimekField.setText("");
        PriimekField.setForeground(Color.black);
    }//GEN-LAST:event_fgpriimek

    private void fgulica(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fgulica
        UlicaField.setText("");
        UlicaField.setForeground(Color.black);
    }//GEN-LAST:event_fgulica

    private void fghisna(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fghisna
        HisnaField.setText("");
        HisnaField.setForeground(Color.black);
    }//GEN-LAST:event_fghisna

    private void fgkraj(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fgkraj
        KrajField.setText("");
        KrajField.setForeground(Color.black);
    }//GEN-LAST:event_fgkraj

    private void APulica(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APulica
        // TODO add your handling code here:
    }//GEN-LAST:event_APulica

    private void ZnamkaFieldfgime(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ZnamkaFieldfgime
        ZnamkaField.setText("");
        ZnamkaField.setForeground(Color.black);
    }//GEN-LAST:event_ZnamkaFieldfgime

    private void ZnamkaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZnamkaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZnamkaFieldActionPerformed

    private void OznakaFieldfgpriimek(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OznakaFieldfgpriimek
        OznakaField.setText("");
        OznakaField.setForeground(Color.black);
    }//GEN-LAST:event_OznakaFieldfgpriimek

    private void PlinRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlinRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlinRadioActionPerformed

    private void RegOznacbaFieldfgime(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RegOznacbaFieldfgime
        RegOznacbaField.setText("");
    }//GEN-LAST:event_RegOznacbaFieldfgime

    private void AOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AOActionPerformed

    private void BrezzavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrezzavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrezzavActionPerformed

    private void ZParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZParkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZParkActionPerformed

    private void ZTretjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZTretjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZTretjaActionPerformed

    private void ZPotnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZPotnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZPotnActionPerformed

    private void KrajRegistracijeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KrajRegistracijeFieldFocusGained
        KrajRegistracijeField.setText("");
        KrajRegistracijeField.setForeground(Color.black);
        
    }//GEN-LAST:event_KrajRegistracijeFieldFocusGained

    private void ImeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ImeFieldFocusLost
        String ime = ImeField.getText().trim();
        if(!ime.matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Ime mora vsebovati samo črke.",
            "Napaka pri vnosu imena",
            JOptionPane.WARNING_MESSAGE);
            
            ImeField.setText("Napaka pri vnosu");
            ImeField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali ime stranke");
        }
    }//GEN-LAST:event_ImeFieldFocusLost

    private void PriimekFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PriimekFieldFocusLost
        if(!PriimekField.getText().matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Priimek mora vsebovati samo črke.",
            "Napaka pri vnosu priimka",
            JOptionPane.WARNING_MESSAGE);
            PriimekField.setText("Napaka pri vnosu");
            PriimekField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali priimek stranke");
        }
    }//GEN-LAST:event_PriimekFieldFocusLost

    private void UlicaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UlicaFieldFocusLost
        String ime = UlicaField.getText().trim();
        if(!ime.matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Ime ulice mora vsebovati samo črke.",
            "Napaka pri vnosu imena ulice",
            JOptionPane.WARNING_MESSAGE);
            
            UlicaField.setText("Napaka pri vnosu");
            UlicaField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali ulico");
        }
    }//GEN-LAST:event_UlicaFieldFocusLost

    private void HisnaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HisnaFieldFocusLost
        String ime = HisnaField.getText().trim();
        if(!ime.matches("^[0-9-A-z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Hišna številka lahko vsebuje le številke in črke.",
            "Napaka pri vnosu Hišne Številke",
            JOptionPane.WARNING_MESSAGE);
            
            HisnaField.setText("Napaka pri vnosu");
            HisnaField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali hišno številko");
        }
    }//GEN-LAST:event_HisnaFieldFocusLost

    private void KrajFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KrajFieldFocusLost
        String ime = KrajField.getText().trim();
        if(!ime.matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Kraj mora vsebovati samo črke.",
            "Napaka pri vnosu kraja",
            JOptionPane.WARNING_MESSAGE);
            
            KrajField.setText("Napaka pri vnosu");
            KrajField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali kraj");
        }
    }//GEN-LAST:event_KrajFieldFocusLost

    private void ZnamkaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ZnamkaFieldFocusLost
        String ime = ZnamkaField.getText().trim();
        if(!ime.matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Znamka mora vsebovati samo črke.",
            "Napaka pri vnosu znamke vozila",
            JOptionPane.WARNING_MESSAGE);
            
            ZnamkaField.setText("Napaka pri vnosu");
            ZnamkaField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali znamko vozila");
        }
    }//GEN-LAST:event_ZnamkaFieldFocusLost

    private void OznakaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OznakaFieldFocusLost
        String ime = OznakaField.getText().trim();
        if(!ime.matches("^[0-9-A-z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Oznaka lahko vsebuje le številke in črke.",
            "Napaka pri vnosu oznake",
            JOptionPane.WARNING_MESSAGE);
            
            OznakaField.setText("Napaka pri vnosu");
            OznakaField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali oznako");
        }
    }//GEN-LAST:event_OznakaFieldFocusLost

    private void KrajRegistracijeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KrajRegistracijeFieldFocusLost
        String ime = KrajRegistracijeField.getText().trim();
        if(!ime.matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(jFrame1,
            "Kraj registracije mora vsebovati samo črke.",
            "Napaka pri vnosu kraja registracije.",
            JOptionPane.WARNING_MESSAGE);
            
            KrajRegistracijeField.setText("Napaka pri vnosu");
            KrajRegistracijeField.setForeground(Color.red);
            status.setText("Status: Napačno ste vpisali kraj registracije");
        }
    }//GEN-LAST:event_KrajRegistracijeFieldFocusLost

    private void AOplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AOplusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AOplusActionPerformed

    private void FranzavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FranzavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FranzavActionPerformed

    private void DRmesecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRmesecActionPerformed
        if(DRmesec.getSelectedIndex() == 1){
            if(DRdan.getSelectedIndex()>28){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec februar ima 29 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DRdan.setSelectedIndex(28);
            }
        }
        if(DRmesec.getSelectedIndex() == 3){
            if(DRdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec april ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DRdan.setSelectedIndex(29);
            }
        }
        if(DRmesec.getSelectedIndex() == 5){
            if(DRdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec junij ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DRdan.setSelectedIndex(29);
            }
        }
        if(DRmesec.getSelectedIndex() == 8){
            if(DRdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec september ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DRdan.setSelectedIndex(29);
            }
        }
        if(DRmesec.getSelectedIndex() == 10){
            if(DRdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec november ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DRdan.setSelectedIndex(29);
            }
        }
    }//GEN-LAST:event_DRmesecActionPerformed

    private void DPmesecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPmesecActionPerformed
        if(DPmesec.getSelectedIndex() == 1){
            if(DPdan.getSelectedIndex()>28){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec februar ima 29 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DPdan.setSelectedIndex(28);
            }
        }
        if(DPmesec.getSelectedIndex() == 3){
            if(DPdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec april ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DPdan.setSelectedIndex(29);
            }
        }
        if(DPmesec.getSelectedIndex() == 5){
            if(DPdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec junij ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DPdan.setSelectedIndex(29);
            }
        }
        if(DPmesec.getSelectedIndex() == 8){
            if(DPdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec september ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DPdan.setSelectedIndex(29);
            }
        }
        if(DPmesec.getSelectedIndex() == 10){
            if(DPdan.getSelectedIndex()>29){
                JOptionPane.showMessageDialog(jFrame1,
                "Mesec november ima 30 dni.",
                "Napaka pri vnosu meseca.",
                JOptionPane.WARNING_MESSAGE);
                status.setText("Status: Napaka pri vnosu dneva je bila popravljena.");
                DPdan.setSelectedIndex(29);
            }
        }
    }//GEN-LAST:event_DPmesecActionPerformed

    private void PonastaviVnoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PonastaviVnoseActionPerformed
        status.setText("Status: Vsa polja so ponastavljena");
        ImeField.setText("Vpišite Ime");
        PriimekField.setText("Vpišite Priimek");
        UlicaField.setText("Vpišite Ulico");
        HisnaField.setText("Vpišite Hišno Številko");
        KrajField.setText("Vpišite Kraj");
        IzkusnjeCombo.setSelectedIndex(0);
        DRdan.setSelectedIndex(0);
        DRmesec.setSelectedIndex(0);
        DRleto.setSelectedIndex(0);
        PostaSpinner.setValue(1000);
        ZnamkaField.setText("Vpišite Znamko");
        OznakaField.setText("Vpišite Oznako");
        VrstaVozilaCombo.setSelectedIndex(0);
        MocSpinner.setValue(1);
        KubSpinner.setValue(1);
        SedeziSpinner.setValue(1);
        BarvaComboBox.setSelectedIndex(0);
        Goriva.clearSelection();
        VrstaVozilaCombo.setSelectedIndex(0);
        
        DPdan.setSelectedIndex(0);
        DPmesec.setSelectedIndex(0);
        DPleto.setSelectedIndex(0);
        
        KrajRegistracijeField.setText("Vpišite Kraj Prve Registracije");
        RegOznacbaField.setText("Vpišite Registracijsko Označbo");
        
        OsnovnoZavarovanje.clearSelection();
        KaskoZavarovanje.clearSelection();
        
        ZStekel.setSelected(false);
        ZPark.setSelected(false);
        ZTretja.setSelected(false);
        ZPotn.setSelected(false);
        ZGum.setSelected(false);
        ZKraji.setSelected(false);
        ZToci.setSelected(false);
    }//GEN-LAST:event_PonastaviVnoseActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String celota = "";
        celota += "Ime: "+ImeField.getText();
        celota += " Priimek: "+PriimekField.getText();
        celota += " Ulica: "+UlicaField.getText();
        celota += " Hišna št: "+HisnaField.getText();
        celota += " Kraj: "+KrajField.getText();
        celota += " Izkušnje: "+IzkusnjeCombo.getSelectedItem().toString();
        celota += " Datum: " + DRdan.getSelectedItem().toString()+". " + DRmesec.getSelectedItem().toString()+". "+ DRleto.getSelectedItem().toString()+".";
        celota += " Pošta: "+PostaSpinner.getValue().toString();
        celota += " Znamka: "+ZnamkaField.getText();
        celota += " Oznaka: "+OznakaField.getText();
        celota += " Vrsta vozila: "+VrstaVozilaCombo.getSelectedItem().toString();
        celota += " Moč: "+MocSpinner.getValue().toString();
        celota += " Prostornina: "+KubSpinner.getValue().toString();
        celota += " Št. sedežev: "+SedeziSpinner.getValue().toString();
        celota += " Barva: "+BarvaComboBox.getSelectedItem().toString();
        if(BencinRadio.isSelected()){
            celota += " Vrsta goriva: "+BencinRadio.getText();
        }
        if(NaftaRadio.isSelected()){
            celota += " Vrsta goriva: "+NaftaRadio.getText();
        }
        if(ElektrikaRadio.isSelected()){
            celota += " Vrsta goriva: "+ElektrikaRadio.getText();
        }
        if(PlinRadio.isSelected()){
            celota += " Vrsta goriva: "+PlinRadio.getText();
        }
        
        celota += " Kraj registracije: "+KrajRegistracijeField.getText();
        celota += " Označba: "+RegOznacbaField.getText();
        celota += " Datum prve registracije: " + DPdan.getSelectedItem().toString()+". " + DPmesec.getSelectedItem().toString()+". "+ DPleto.getSelectedItem().toString()+".";
        celota += " Izbire: ";
        if(ZStekel.isSelected()){
            celota += ZStekel.getText();
        }
        if(ZPark.isSelected()){
            celota += ZPark.getText();
        }
        if(ZTretja.isSelected()){
            celota += ZTretja.getText();
        }
        if(ZPotn.isSelected()){
            celota += ZPotn.getText();
        }
        if(ZGum.isSelected()){
            celota += ZGum.getText();
        }
        if(ZKraji.isSelected()){
            celota += ZKraji.getText();
        }
        if(ZToci.isSelected()){
            celota += ZToci.getText();
        }
        
        if(AO.isSelected()){
            celota += " Osnovno zavarovanje: "+AO.getText();
        }
        if(AOplus.isSelected()){
            celota += " Osnovno zavarovanje: "+AOplus.getText();
        }
        
        if(Polnozav.isSelected()){
            celota += " Kasko zavarovanje: "+Polnozav.getText();
        }
        if(Franzav.isSelected()){
            celota += " Kasko zavarovanje: "+Franzav.getText();
        }
        if(Brezzav.isSelected()){
            celota += " Kasko zavarovanje: "+Brezzav.getText();
        }
        
        
        CelotaSave.setText(celota);
       
        if(jfc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
              File f = jfc.getSelectedFile();
              status.setText("Datoteka: " + f.getName());
              try{
                  CelotaSave.write(new FileWriter(f));
                  status.setText("Status: Datoteka je bila shranjena.");
              }catch(IOException e){
                  status.setText("Napaka pri shranjevanju datoteke: " + f.getName());
              }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void PomocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PomocActionPerformed
        
    }//GEN-LAST:event_PomocActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(jFrame1,
                "Kontakt programerja: jan@novak.si",
                "Kontakt",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AO;
    private javax.swing.JRadioButton AOplus;
    private javax.swing.JComboBox<String> BarvaComboBox;
    private javax.swing.JLabel BarvaLabel;
    private javax.swing.JRadioButton BencinRadio;
    private javax.swing.JRadioButton Brezzav;
    private javax.swing.JTextField CelotaSave;
    private javax.swing.JComboBox<String> DPdan;
    private javax.swing.JComboBox<String> DPleto;
    private javax.swing.JComboBox<String> DPmesec;
    private javax.swing.JComboBox<String> DRdan;
    private javax.swing.JComboBox<String> DRleto;
    private javax.swing.JComboBox<String> DRmesec;
    private javax.swing.JLabel DatumRegistracijeLabel;
    private javax.swing.JLabel DatumRojLabel;
    private javax.swing.JRadioButton ElektrikaRadio;
    private javax.swing.JRadioButton Franzav;
    private javax.swing.ButtonGroup Goriva;
    private javax.swing.JLabel GorivoLabel;
    private javax.swing.JTextField HisnaField;
    private javax.swing.JLabel HisnaLabel;
    private javax.swing.JTextField ImeField;
    private javax.swing.JLabel ImeLabel;
    private javax.swing.JComboBox<String> IzkusnjeCombo;
    private javax.swing.JLabel IzkusnjeLabel;
    private javax.swing.ButtonGroup KaskoZavarovanje;
    private javax.swing.JTextField KrajField;
    private javax.swing.JLabel KrajLabel;
    private javax.swing.JTextField KrajRegistracijeField;
    private javax.swing.JLabel KrajRegistracijeLabel;
    private javax.swing.JLabel KrajRegistracijeNapaka;
    private javax.swing.JLabel KubLabel;
    private javax.swing.JSpinner KubSpinner;
    private javax.swing.JLabel MocLabel;
    private javax.swing.JLabel MocLabel2;
    private javax.swing.JSpinner MocSpinner;
    private javax.swing.JRadioButton NaftaRadio;
    private javax.swing.ButtonGroup OsnovnoZavarovanje;
    private javax.swing.JTextField OznakaField;
    private javax.swing.JLabel OznakaLabel;
    private javax.swing.JPanel Panela_Vozilo;
    private javax.swing.JPanel Panela_Zavarovanec;
    private javax.swing.JPanel Panela_Zavarovanje;
    private javax.swing.JRadioButton PlinRadio;
    private javax.swing.JPanel PodatkiORegistraciji;
    private javax.swing.JPanel PodatkiOZavarovancu;
    private javax.swing.JPanel PodatkiOZavarovancu1;
    private javax.swing.JPanel PodatkiOZavarovanju;
    private javax.swing.JRadioButton Polnozav;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JMenuItem PonastaviVnose;
    private javax.swing.JLabel PostaLabel;
    private javax.swing.JSpinner PostaSpinner;
    private javax.swing.JTextField PriimekField;
    private javax.swing.JLabel PriimekLabel;
    private javax.swing.JPanel Prosta;
    private javax.swing.JPanel Prosta1;
    private javax.swing.JPanel Prosta2;
    private javax.swing.JTextField RegOznacbaField;
    private javax.swing.JLabel RegOznacbaLabel;
    private javax.swing.JLabel SedeziLabel;
    private javax.swing.JSpinner SedeziSpinner;
    private javax.swing.JTextField UlicaField;
    private javax.swing.JLabel UlicaLabel;
    private javax.swing.JComboBox<String> VrstaVozilaCombo;
    private javax.swing.JLabel VrstaVozilaLabel;
    private javax.swing.JCheckBox ZGum;
    private javax.swing.JCheckBox ZKraji;
    private javax.swing.JCheckBox ZPark;
    private javax.swing.JCheckBox ZPotn;
    private javax.swing.JCheckBox ZStekel;
    private javax.swing.JCheckBox ZToci;
    private javax.swing.JCheckBox ZTretja;
    private javax.swing.JTextField ZnamkaField;
    private javax.swing.JLabel ZnamkaLabel;
    private javax.swing.JLabel ZnamkaLabel2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JFileChooser jfc;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
